### ISSUE TITLE
'openBlock' is not exported

### ISSUE THREAD

**Issue by MrSunshyne** [Withenex/vanilla-tilt-vue#9]
Thanks for building this ! 

I'm using it in a nuxt3 application, and it runs great in dev mode. 

But when I build the application, I get the following error: 

```
'openBlock' is not exported by node_modules/vanilla-tilt-vue/node_modules/vue/dist/vue.runtime.esm.js, imported by node_modules/vanilla-tilt-vue/src/components/tilt.vue
```

```
17: }
18: 
19: import { renderSlot as _renderSlot, normalizeClass as _normalizeClass, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"
                                                                           ^
20: 
21: function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {

 ERROR  'openBlock' is not exported by node_modules/vanilla-tilt-vue/node_modules/vue/dist/vue.runtime.esm.js, imported by node_modules/vanilla-tilt-vue/src/components/tilt.vue

  at error (node_modules/rollup/dist/shared/rollup.js:198:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:12659:16)
  at Module.traceVariable (node_modules/rollup/dist/shared/rollup.js:13018:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/shared/rollup.js:11674:39)
  at FunctionScope.findVariable (node_modules/rollup/dist/shared/rollup.js:6538:38)
  at ChildScope.findVariable (node_modules/rollup/dist/shared/rollup.js:6538:38)
  at Identifier.bind (node_modules/rollup/dist/shared/rollup.js:7600:40)
  at CallExpression.bind (node_modules/rollup/dist/shared/rollup.js:5369:23)
  at CallExpression.bind (node_modules/rollup/dist/shared/rollup.js:9098:15)
  at SequenceExpression.bind (node_modules/rollup/dist/shared/rollup.js:5365:73)
```

Any pointers would help :D

**Comment by MrSunshyne** [comment]
I was able to resolve it as follows

//nuxt.config.ts

```
export default defineNuxtConfig({
  ...,
  vite: {
    resolve: { dedupe: ['vue'] },
  }
```
